package classes;


import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 
 * 
 * Jefferson Carvalho
 * jeffersoncarvalho60@outlook.com
 * 
 */

public class TelaAdm extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdm
     */
    Aviso dadosAviso = new Aviso();
    Usuario dadosUsuario = new Usuario();
    Chamado dadosChamado = new Chamado();

    public static DefaultTableModel mdlChamados;

    public TelaAdm(Login tmpLogin) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        preencheBarras(tmpLogin.getLogin(), Integer.toString(tmpLogin.getId()));
        
        setColor(btnGerenciarChamados);

        mdlChamados = (DefaultTableModel) tblChamados.getModel();
        
        carregaTabelaChamados();

        tblChamados.addMouseListener(new MouseAdapter() {

            public void mouseClicked(MouseEvent evt) {
                String tmpCodigo;

                tmpCodigo = tblChamados.getValueAt(tblChamados.getSelectedRow(), 0).toString();

                try {
                    Chamado tmpChamado = new Chamado();

                    tmpChamado = ChamadoDAO.consultaChamado(tmpCodigo);

                    System.out.println(tmpChamado.getDescricao());

                    txtDescricao.setText(tmpChamado.getDescricao());
                } catch (Exception erro) {
                    JOptionPane.showMessageDialog(null, erro.getMessage());
                }
            }

        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        btnGerenciarChamados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadastrarUsuarios = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        btnSair = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnNovoAviso = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        frameGerenciarChamados = new javax.swing.JInternalFrame();
        ((BasicInternalFrameUI)frameGerenciarChamados.getUI()).setNorthPane(null);
        frameGerenciarChamados.setBorder(null);
        pnlChamado = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChamados = new javax.swing.JTable();
        btnAlterarChamado = new java.awt.Button();
        button2 = new java.awt.Button();
        pnlBarra = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblSenha1 = new javax.swing.JLabel();
        frameInserirAviso = new javax.swing.JInternalFrame();
        ((BasicInternalFrameUI)frameInserirAviso.getUI()).setNorthPane(null);
        frameGerenciarChamados.setBorder(null);
        pnlChamado1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtDescricaoAviso = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        btnEnviarAviso = new java.awt.Button();
        jLabel23 = new javax.swing.JLabel();
        txtAssunto = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        pnlBarra1 = new javax.swing.JPanel();
        lblUsuario2 = new javax.swing.JLabel();
        lblUsuario11 = new javax.swing.JLabel();
        lblSenha2 = new javax.swing.JLabel();
        lblSenha11 = new javax.swing.JLabel();
        frameCadastrarUsuario = new javax.swing.JInternalFrame();
        ((BasicInternalFrameUI)frameCadastrarUsuario.getUI()).setNorthPane(null);
        frameGerenciarChamados.setBorder(null);
        pnlChamado2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        btnCadastrarUsuario = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jcbSetor = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtUsuario = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        pnlBarra2 = new javax.swing.JPanel();
        lblUsuario3 = new javax.swing.JLabel();
        lblUsuario12 = new javax.swing.JLabel();
        lblSenha3 = new javax.swing.JLabel();
        lblSenha12 = new javax.swing.JLabel();
        frameAlterarChamado = new javax.swing.JInternalFrame();
        ((BasicInternalFrameUI)frameAlterarChamado.getUI()).setNorthPane(null);
        frameAlterarChamado.setBorder(null);
        pnlChamado3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        btnAlterarChamado1 = new java.awt.Button();
        jLabel33 = new javax.swing.JLabel();
        jcbUrgencia = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jcbImpacto = new javax.swing.JComboBox<>();
        jcbStatus = new javax.swing.JComboBox<>();
        pnlBarra3 = new javax.swing.JPanel();
        lblUsuario4 = new javax.swing.JLabel();
        lblUsuario13 = new javax.swing.JLabel();
        lblSenha4 = new javax.swing.JLabel();
        lblSenha13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        frameConcluirChamado = new javax.swing.JInternalFrame();
        ((BasicInternalFrameUI)frameConcluirChamado.getUI()).setNorthPane(null);
        frameConcluirChamado.setBorder(null);
        pnlChamado4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        pnlBarra4 = new javax.swing.JPanel();
        lblUsuario5 = new javax.swing.JLabel();
        lblUsuario14 = new javax.swing.JLabel();
        lblSenha5 = new javax.swing.JLabel();
        lblSenha14 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        btnCadastrarUsuario1 = new java.awt.Button();
        jSeparator12 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPrincipal.setBackground(new java.awt.Color(0, 0, 0));
        pnlPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlPrincipal.setPreferredSize(new java.awt.Dimension(875, 508));

        pnlMenu.setBackground(new java.awt.Color(0, 120, 51));

        btnGerenciarChamados.setBackground(new java.awt.Color(0, 153, 50));
        btnGerenciarChamados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGerenciarChamadosMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/white-cogwheel.png"))); // NOI18N
        jLabel1.setText("   Gerenciar chamados");

        javax.swing.GroupLayout btnGerenciarChamadosLayout = new javax.swing.GroupLayout(btnGerenciarChamados);
        btnGerenciarChamados.setLayout(btnGerenciarChamadosLayout);
        btnGerenciarChamadosLayout.setHorizontalGroup(
            btnGerenciarChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGerenciarChamadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnGerenciarChamadosLayout.setVerticalGroup(
            btnGerenciarChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnGerenciarChamadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCadastrarUsuarios.setBackground(new java.awt.Color(0, 153, 50));
        btnCadastrarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCadastrarUsuariosMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clipboard-with-pencil-.png"))); // NOI18N
        jLabel3.setText("    Cadastrar Usuarios");

        javax.swing.GroupLayout btnCadastrarUsuariosLayout = new javax.swing.GroupLayout(btnCadastrarUsuarios);
        btnCadastrarUsuarios.setLayout(btnCadastrarUsuariosLayout);
        btnCadastrarUsuariosLayout.setHorizontalGroup(
            btnCadastrarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCadastrarUsuariosLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnCadastrarUsuariosLayout.setVerticalGroup(
            btnCadastrarUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCadastrarUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fix Me !!!");

        btnSair.setBackground(new java.awt.Color(0, 153, 50));
        btnSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSairMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout.png"))); // NOI18N
        jLabel6.setText("    Sair");

        javax.swing.GroupLayout btnSairLayout = new javax.swing.GroupLayout(btnSair);
        btnSair.setLayout(btnSairLayout);
        btnSairLayout.setHorizontalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSairLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnSairLayout.setVerticalGroup(
            btnSairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSairLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovoAviso.setBackground(new java.awt.Color(0, 153, 50));
        btnNovoAviso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnNovoAvisoMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        jLabel2.setText("   Novo Aviso");

        javax.swing.GroupLayout btnNovoAvisoLayout = new javax.swing.GroupLayout(btnNovoAviso);
        btnNovoAviso.setLayout(btnNovoAvisoLayout);
        btnNovoAvisoLayout.setHorizontalGroup(
            btnNovoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnNovoAvisoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnNovoAvisoLayout.setVerticalGroup(
            btnNovoAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnNovoAvisoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnGerenciarChamados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCadastrarUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNovoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(btnGerenciarChamados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCadastrarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(632, 500));
        jDesktopPane1.setLayout(new java.awt.FlowLayout());

        frameGerenciarChamados.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        frameGerenciarChamados.setPreferredSize(new java.awt.Dimension(622, 493));
        frameGerenciarChamados.setVisible(true);

        pnlChamado.setBackground(new java.awt.Color(255, 255, 255));
        pnlChamado.setPreferredSize(new java.awt.Dimension(661, 490));

        jPanel4.setBackground(new java.awt.Color(0, 153, 51));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Últimos chamados:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel13.setText("Clique em um chamado para ver a descrição:");

        txtDescricao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Meiryo UI", 0, 24)); // NOI18N
        jLabel16.setText("x");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        tblChamados.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        tblChamados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Categoria", "Data", "Urgência", "Impacto", "Prioridade", "Status"
            }
        ));
        jScrollPane2.setViewportView(tblChamados);
        if (tblChamados.getColumnModel().getColumnCount() > 0) {
            tblChamados.getColumnModel().getColumn(0).setMinWidth(0);
            tblChamados.getColumnModel().getColumn(0).setPreferredWidth(0);
            tblChamados.getColumnModel().getColumn(1).setPreferredWidth(30);
            tblChamados.getColumnModel().getColumn(2).setPreferredWidth(40);
            tblChamados.getColumnModel().getColumn(3).setMinWidth(0);
            tblChamados.getColumnModel().getColumn(3).setPreferredWidth(10);
            tblChamados.getColumnModel().getColumn(4).setMinWidth(0);
            tblChamados.getColumnModel().getColumn(4).setPreferredWidth(10);
            tblChamados.getColumnModel().getColumn(5).setMinWidth(0);
            tblChamados.getColumnModel().getColumn(5).setPreferredWidth(10);
            tblChamados.getColumnModel().getColumn(6).setMinWidth(0);
        }

        btnAlterarChamado.setBackground(new java.awt.Color(0, 153, 51));
        btnAlterarChamado.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        btnAlterarChamado.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarChamado.setLabel("Alterar Chamado");
        btnAlterarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarChamadoActionPerformed(evt);
            }
        });

        button2.setBackground(new java.awt.Color(0, 153, 51));
        button2.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("Concluir Chamado");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        pnlBarra.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblUsuario.setText("Usuário:");

        lblUsuario1.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblUsuario1.setText("jLabel19");

        lblSenha.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblSenha.setText("ID:");

        lblSenha1.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblSenha1.setText("jLabel19");

        javax.swing.GroupLayout pnlBarraLayout = new javax.swing.GroupLayout(pnlBarra);
        pnlBarra.setLayout(pnlBarraLayout);
        pnlBarraLayout.setHorizontalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario1)
                .addGap(60, 60, 60)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha1)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        pnlBarraLayout.setVerticalGroup(
            pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarraLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pnlBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario)
                    .addComponent(lblUsuario1)
                    .addComponent(lblSenha)
                    .addComponent(lblSenha1)))
        );

        javax.swing.GroupLayout pnlChamadoLayout = new javax.swing.GroupLayout(pnlChamado);
        pnlChamado.setLayout(pnlChamadoLayout);
        pnlChamadoLayout.setHorizontalGroup(
            pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamadoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addGroup(pnlChamadoLayout.createSequentialGroup()
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addGroup(pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAlterarChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(pnlChamadoLayout.createSequentialGroup()
                    .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlChamadoLayout.setVerticalGroup(
            pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamadoLayout.createSequentialGroup()
                .addGroup(pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(pnlChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChamadoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAlterarChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout frameGerenciarChamadosLayout = new javax.swing.GroupLayout(frameGerenciarChamados.getContentPane());
        frameGerenciarChamados.getContentPane().setLayout(frameGerenciarChamadosLayout);
        frameGerenciarChamadosLayout.setHorizontalGroup(
            frameGerenciarChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChamado, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frameGerenciarChamadosLayout.setVerticalGroup(
            frameGerenciarChamadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChamado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDesktopPane1.add(frameGerenciarChamados);

        frameInserirAviso.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        frameInserirAviso.setVisible(false);

        pnlChamado1.setBackground(new java.awt.Color(255, 255, 255));
        pnlChamado1.setMaximumSize(new java.awt.Dimension(632, 483));
        pnlChamado1.setName(""); // NOI18N
        pnlChamado1.setPreferredSize(new java.awt.Dimension(661, 483));

        jPanel5.setBackground(new java.awt.Color(0, 153, 51));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Inserir novo aviso:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel19.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel19.setText("Descrição:");

        txtDescricaoAviso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel22.setFont(new java.awt.Font("Meiryo UI", 0, 24)); // NOI18N
        jLabel22.setText("x");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel22MousePressed(evt);
            }
        });

        btnEnviarAviso.setBackground(new java.awt.Color(0, 153, 51));
        btnEnviarAviso.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        btnEnviarAviso.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarAviso.setLabel("Enviar Aviso");
        btnEnviarAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarAvisoActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel23.setText("Assunto:");

        txtAssunto.setBorder(null);

        pnlBarra1.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblUsuario2.setText("Usuário:");

        lblUsuario11.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblUsuario11.setText("jLabel19");

        lblSenha2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblSenha2.setText("ID:");

        lblSenha11.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblSenha11.setText("jLabel19");

        javax.swing.GroupLayout pnlBarra1Layout = new javax.swing.GroupLayout(pnlBarra1);
        pnlBarra1.setLayout(pnlBarra1Layout);
        pnlBarra1Layout.setHorizontalGroup(
            pnlBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario11)
                .addGap(60, 60, 60)
                .addComponent(lblSenha2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha11)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlBarra1Layout.setVerticalGroup(
            pnlBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra1Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pnlBarra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario2)
                    .addComponent(lblUsuario11)
                    .addComponent(lblSenha2)
                    .addComponent(lblSenha11)))
        );

        javax.swing.GroupLayout pnlChamado1Layout = new javax.swing.GroupLayout(pnlChamado1);
        pnlChamado1.setLayout(pnlChamado1Layout);
        pnlChamado1Layout.setHorizontalGroup(
            pnlChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamado1Layout.createSequentialGroup()
                .addGroup(pnlChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlChamado1Layout.createSequentialGroup()
                        .addComponent(pnlBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlChamado1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChamado1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(pnlChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEnviarAviso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel23)
                                    .addComponent(txtAssunto)
                                    .addComponent(jSeparator4)
                                    .addComponent(txtDescricaoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                                    .addComponent(jSeparator5)))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        pnlChamado1Layout.setVerticalGroup(
            pnlChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamado1Layout.createSequentialGroup()
                .addGroup(pnlChamado1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(9, 9, 9)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtDescricaoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEnviarAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameInserirAvisoLayout = new javax.swing.GroupLayout(frameInserirAviso.getContentPane());
        frameInserirAviso.getContentPane().setLayout(frameInserirAvisoLayout);
        frameInserirAvisoLayout.setHorizontalGroup(
            frameInserirAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChamado1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frameInserirAvisoLayout.setVerticalGroup(
            frameInserirAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameInserirAvisoLayout.createSequentialGroup()
                .addComponent(pnlChamado1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(frameInserirAviso);

        frameCadastrarUsuario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        frameCadastrarUsuario.setVisible(false);

        pnlChamado2.setBackground(new java.awt.Color(255, 255, 255));
        pnlChamado2.setMaximumSize(new java.awt.Dimension(633, 483));
        pnlChamado2.setPreferredSize(new java.awt.Dimension(633, 483));

        jPanel6.setBackground(new java.awt.Color(0, 153, 51));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cadastrar novo usuário:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel27.setFont(new java.awt.Font("Meiryo UI", 0, 24)); // NOI18N
        jLabel27.setText("x");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel27MousePressed(evt);
            }
        });

        btnCadastrarUsuario.setBackground(new java.awt.Color(0, 153, 51));
        btnCadastrarUsuario.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        btnCadastrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarUsuario.setLabel("Cadastrar Usuário");
        btnCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuarioActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel10.setText("Email:");

        jLabel17.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel17.setText("Setor:");

        jLabel18.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel18.setText("Senha de acesso:");

        txtNome.setText("Nome do usuário");
        txtNome.setBorder(null);
        txtNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeFocusGained(evt);
            }
        });

        txtEmail.setText("Digite o email do usuário");
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
        });

        jcbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "Contabilidade", "Recursos Humanos" }));

        jLabel29.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel29.setText("Nome:");

        txtUsuario.setText("Digite um login de acesso");
        txtUsuario.setBorder(null);
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel30.setText("Usuário:");

        txtSenha.setText("Digite uma senha de acesso");
        txtSenha.setBorder(null);
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
        });

        pnlBarra2.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblUsuario3.setText("Usuário:");

        lblUsuario12.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblUsuario12.setText("jLabel19");

        lblSenha3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblSenha3.setText("ID:");

        lblSenha12.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblSenha12.setText("jLabel19");

        javax.swing.GroupLayout pnlBarra2Layout = new javax.swing.GroupLayout(pnlBarra2);
        pnlBarra2.setLayout(pnlBarra2Layout);
        pnlBarra2Layout.setHorizontalGroup(
            pnlBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario12)
                .addGap(60, 60, 60)
                .addComponent(lblSenha3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha12)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlBarra2Layout.setVerticalGroup(
            pnlBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra2Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pnlBarra2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario3)
                    .addComponent(lblUsuario12)
                    .addComponent(lblSenha3)
                    .addComponent(lblSenha12)))
        );

        javax.swing.GroupLayout pnlChamado2Layout = new javax.swing.GroupLayout(pnlChamado2);
        pnlChamado2.setLayout(pnlChamado2Layout);
        pnlChamado2Layout.setHorizontalGroup(
            pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamado2Layout.createSequentialGroup()
                .addComponent(pnlBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(pnlChamado2Layout.createSequentialGroup()
                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChamado2Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlChamado2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(251, 251, 251)
                                .addComponent(jLabel10))
                            .addGroup(pnlChamado2Layout.createSequentialGroup()
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlChamado2Layout.createSequentialGroup()
                                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel18)
                                    .addGroup(pnlChamado2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(106, 106, 106)
                                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jcbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlChamado2Layout.setVerticalGroup(
            pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChamado2Layout.createSequentialGroup()
                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(pnlBarra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlChamado2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChamado2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(16, 16, 16)
                        .addComponent(jcbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlChamado2Layout.createSequentialGroup()
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addComponent(btnCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout frameCadastrarUsuarioLayout = new javax.swing.GroupLayout(frameCadastrarUsuario.getContentPane());
        frameCadastrarUsuario.getContentPane().setLayout(frameCadastrarUsuarioLayout);
        frameCadastrarUsuarioLayout.setHorizontalGroup(
            frameCadastrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChamado2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frameCadastrarUsuarioLayout.setVerticalGroup(
            frameCadastrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCadastrarUsuarioLayout.createSequentialGroup()
                .addComponent(pnlChamado2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(frameCadastrarUsuario);

        frameAlterarChamado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        frameAlterarChamado.setVisible(false);

        pnlChamado3.setBackground(new java.awt.Color(255, 255, 255));
        pnlChamado3.setMaximumSize(new java.awt.Dimension(637, 483));
        pnlChamado3.setPreferredSize(new java.awt.Dimension(637, 483));
        pnlChamado3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 153, 51));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Alterar Chamado");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlChamado3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, -1, -1));

        jLabel32.setFont(new java.awt.Font("Meiryo UI", 0, 24)); // NOI18N
        jLabel32.setText("x");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel32MousePressed(evt);
            }
        });
        pnlChamado3.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 0, 29, -1));

        btnAlterarChamado1.setBackground(new java.awt.Color(0, 153, 51));
        btnAlterarChamado1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        btnAlterarChamado1.setForeground(new java.awt.Color(255, 255, 255));
        btnAlterarChamado1.setLabel("Alterar Chamado");
        btnAlterarChamado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarChamado1ActionPerformed(evt);
            }
        });
        pnlChamado3.add(btnAlterarChamado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 388, -1, 37));

        jLabel33.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel33.setText("Status:");
        pnlChamado3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 278, -1, 32));

        jcbUrgencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Média", "Baixa" }));
        pnlChamado3.add(jcbUrgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 173, 152, 30));

        jLabel34.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel34.setText("Urgência:");
        pnlChamado3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 138, -1, -1));

        jLabel35.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel35.setText("Impacto:");
        pnlChamado3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 204, -1, 32));

        jcbImpacto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alto", "Médio", "Baixo" }));
        pnlChamado3.add(jcbImpacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 242, 152, 30));

        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberto", "Em andamento", "Concluído" }));
        pnlChamado3.add(jcbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 321, 152, 30));

        pnlBarra3.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblUsuario4.setText("Usuário:");

        lblUsuario13.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblUsuario13.setText("jLabel19");

        lblSenha4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblSenha4.setText("ID:");

        lblSenha13.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblSenha13.setText("jLabel19");

        javax.swing.GroupLayout pnlBarra3Layout = new javax.swing.GroupLayout(pnlBarra3);
        pnlBarra3.setLayout(pnlBarra3Layout);
        pnlBarra3Layout.setHorizontalGroup(
            pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario13)
                .addGap(60, 60, 60)
                .addComponent(lblSenha4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha13)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlBarra3Layout.setVerticalGroup(
            pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pnlBarra3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario4)
                    .addComponent(lblUsuario13)
                    .addComponent(lblSenha4)
                    .addComponent(lblSenha13)))
        );

        pnlChamado3.add(pnlBarra3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impacto-urgencia.png"))); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlChamado3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Prioridade.png"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlChamado3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        javax.swing.GroupLayout frameAlterarChamadoLayout = new javax.swing.GroupLayout(frameAlterarChamado.getContentPane());
        frameAlterarChamado.getContentPane().setLayout(frameAlterarChamadoLayout);
        frameAlterarChamadoLayout.setHorizontalGroup(
            frameAlterarChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChamado3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frameAlterarChamadoLayout.setVerticalGroup(
            frameAlterarChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameAlterarChamadoLayout.createSequentialGroup()
                .addComponent(pnlChamado3, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(frameAlterarChamado);

        frameConcluirChamado.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        frameConcluirChamado.setVisible(false);

        pnlChamado4.setBackground(new java.awt.Color(255, 255, 255));
        pnlChamado4.setMaximumSize(new java.awt.Dimension(637, 483));
        pnlChamado4.setPreferredSize(new java.awt.Dimension(637, 483));
        pnlChamado4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 153, 51));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Concluir Chamado:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator10, javax.swing.GroupLayout.DEFAULT_SIZE, 11, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlChamado4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, -1, -1));

        jLabel36.setFont(new java.awt.Font("Meiryo UI", 0, 24)); // NOI18N
        jLabel36.setText("x");
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel36MousePressed(evt);
            }
        });
        pnlChamado4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 0, 29, -1));

        pnlBarra4.setBackground(new java.awt.Color(255, 255, 255));

        lblUsuario5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblUsuario5.setText("Usuário:");

        lblUsuario14.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblUsuario14.setText("matheus");

        lblSenha5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        lblSenha5.setText("ID:");

        lblSenha14.setFont(new java.awt.Font("Meiryo UI", 0, 16)); // NOI18N
        lblSenha14.setText("3");

        javax.swing.GroupLayout pnlBarra4Layout = new javax.swing.GroupLayout(pnlBarra4);
        pnlBarra4.setLayout(pnlBarra4Layout);
        pnlBarra4Layout.setHorizontalGroup(
            pnlBarra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBarra4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario14)
                .addGap(60, 60, 60)
                .addComponent(lblSenha5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSenha14)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlBarra4Layout.setVerticalGroup(
            pnlBarra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBarra4Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pnlBarra4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuario5)
                    .addComponent(lblUsuario14)
                    .addComponent(lblSenha5)
                    .addComponent(lblSenha14)))
        );

        pnlChamado4.add(pnlBarra4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel31.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel31.setText("Resolvido por:");
        pnlChamado4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 40));

        txtNome1.setText("Matheus ");
        txtNome1.setBorder(null);
        txtNome1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNome1FocusGained(evt);
            }
        });
        pnlChamado4.add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 370, -1));

        jLabel40.setFont(new java.awt.Font("Meiryo UI", 0, 18)); // NOI18N
        jLabel40.setText("Solução:");
        pnlChamado4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 40));

        btnCadastrarUsuario1.setBackground(new java.awt.Color(0, 153, 51));
        btnCadastrarUsuario1.setFont(new java.awt.Font("Meiryo UI", 0, 14)); // NOI18N
        btnCadastrarUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarUsuario1.setLabel("Concuir Chamado");
        btnCadastrarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarUsuario1ActionPerformed(evt);
            }
        });
        pnlChamado4.add(btnCadastrarUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 40));
        pnlChamado4.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 370, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\nReiniciar os servidores e roteadores.");
        jScrollPane3.setViewportView(jTextArea2);

        pnlChamado4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, -1));

        javax.swing.GroupLayout frameConcluirChamadoLayout = new javax.swing.GroupLayout(frameConcluirChamado.getContentPane());
        frameConcluirChamado.getContentPane().setLayout(frameConcluirChamadoLayout);
        frameConcluirChamadoLayout.setHorizontalGroup(
            frameConcluirChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChamado4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        frameConcluirChamadoLayout.setVerticalGroup(
            frameConcluirChamadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameConcluirChamadoLayout.createSequentialGroup()
                .addComponent(pnlChamado4, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDesktopPane1.add(frameConcluirChamado);

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
            .addComponent(pnlMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void gravaAviso() {

        dadosAviso.setAssunto(txtAssunto.getText());
        dadosAviso.setDescricao(txtDescricaoAviso.getText());
        dadosAviso.setData(dadosAviso.getDataHora(0)); // 0 para data
        dadosAviso.setHora(dadosAviso.getDataHora(1)); // 1 para hora

    }

    public void gravaUsuario() {

        dadosUsuario.setNome(txtNome.getText());
        dadosUsuario.setEmail(txtEmail.getText());
        dadosUsuario.setSetor(jcbSetor.getSelectedItem().toString());
        dadosUsuario.setUsuario(txtUsuario.getText());
        dadosUsuario.setSenha(txtSenha.getText());

    }
    
    public int verificaPrioridade(){
        int tmpPrioridade = 0;
        
        if (dadosChamado.getImpacto() == "Alto" && dadosChamado.getUrgencia() == "Alta") {
            tmpPrioridade = 1;
        }else if(dadosChamado.getImpacto() == "Alto" && dadosChamado.getUrgencia() == "Média"){
            tmpPrioridade = 2;
        }else if(dadosChamado.getImpacto() == "Alto" && dadosChamado.getUrgencia() == "Baixa"){
            tmpPrioridade = 3;
        }else if(dadosChamado.getImpacto() == "Médio" && dadosChamado.getUrgencia() == "Alta"){
            tmpPrioridade = 2;
        }else if(dadosChamado.getImpacto() == "Médio" && dadosChamado.getUrgencia() == "Média"){
            tmpPrioridade = 3;
        }else if(dadosChamado.getImpacto() == "Médio" && dadosChamado.getUrgencia() == "Baixa"){
            tmpPrioridade = 4;
        }else if(dadosChamado.getImpacto() == "Baixo" && dadosChamado.getUrgencia() == "Alta"){
            tmpPrioridade = 3;
        }else if(dadosChamado.getImpacto() == "Baixo" && dadosChamado.getUrgencia() == "Média"){
            tmpPrioridade = 4;
        }else if(dadosChamado.getImpacto() == "Baixo" && dadosChamado.getUrgencia() == "Baixa"){
            tmpPrioridade = 5;
        }
        
        
        return tmpPrioridade;
    }

    public void carregaTabelaChamados() {

        while (mdlChamados.getRowCount() > 0) {
            mdlChamados.removeRow(0);
        }

        try {
            List<Chamado> vetorChamado = new ArrayList<Chamado>();

            vetorChamado = ChamadoDAO.listaChamadosAdm();

            for (Chamado chamadoAtual : vetorChamado) {
                String dadosChamado[] = new String[7];

                dadosChamado[0] = chamadoAtual.getID();
                dadosChamado[1] = chamadoAtual.getSubCategoria();
                dadosChamado[2] = chamadoAtual.getData();
                dadosChamado[3] = chamadoAtual.getUrgencia();
                dadosChamado[4] = chamadoAtual.getImpacto();
                dadosChamado[5] = chamadoAtual.getPrioridade();
                dadosChamado[6] = chamadoAtual.getStatus();

                mdlChamados.addRow(dadosChamado);

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }
    
    public void preencheBarras(String tmpUsuario, String tmpSenha){
        lblUsuario1.setText(tmpUsuario);
        lblSenha1.setText(tmpSenha);
        
        lblUsuario11.setText(tmpUsuario);
        lblSenha11.setText(tmpSenha);
        
        lblUsuario12.setText(tmpUsuario);
        lblSenha12.setText(tmpSenha);
        
        lblUsuario13.setText(tmpUsuario);
        lblSenha13.setText(tmpSenha);
    }

    public void limpaCamposAviso() {
        txtAssunto.setText("");
        txtDescricaoAviso.setText("");

    }

    public void limpaCamposUsuario() {
        txtNome.setText("");
        txtEmail.setText("");
        txtUsuario.setText("");
        txtSenha.setText("");

    }

    private void btnGerenciarChamadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGerenciarChamadosMousePressed
        setColor(btnGerenciarChamados);
        resetColor(btnNovoAviso);
        resetColor(btnCadastrarUsuarios);
        resetColor(btnSair);

        frameInserirAviso.setVisible(false);
        frameCadastrarUsuario.setVisible(false);
        frameGerenciarChamados.setVisible(true);

        carregaTabelaChamados();

    }//GEN-LAST:event_btnGerenciarChamadosMousePressed

    private void btnCadastrarUsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarUsuariosMousePressed
        setColor(btnCadastrarUsuarios);
        resetColor(btnGerenciarChamados);
        resetColor(btnNovoAviso);
        resetColor(btnSair);

        frameGerenciarChamados.setVisible(false);
        frameInserirAviso.setVisible(false);
        frameCadastrarUsuario.setVisible(true);


    }//GEN-LAST:event_btnCadastrarUsuariosMousePressed

    private void btnSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairMousePressed
        setColor(btnSair);
        resetColor(btnGerenciarChamados);
        resetColor(btnNovoAviso);
        resetColor(btnCadastrarUsuarios);

        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_btnSairMousePressed

    private void btnNovoAvisoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoAvisoMousePressed
        setColor(btnNovoAviso);
        resetColor(btnGerenciarChamados);
        resetColor(btnCadastrarUsuarios);
        resetColor(btnSair);

        frameCadastrarUsuario.setVisible(false);
        frameGerenciarChamados.setVisible(false);
        frameInserirAviso.setVisible(true);

    }//GEN-LAST:event_btnNovoAvisoMousePressed

    private void jLabel27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MousePressed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jLabel27MousePressed

    private void btnCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuarioActionPerformed
        gravaUsuario();

        try {
            UsuarioDAO.cadastraUsuario(dadosUsuario);
            limpaCamposUsuario();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o usuário!!!");
        }
    }//GEN-LAST:event_btnCadastrarUsuarioActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        if (tblChamados.getSelectedRowCount() != 0) {

            dadosChamado.setID(tblChamados.getValueAt(tblChamados.getSelectedRow(), 0).toString());

            frameGerenciarChamados.setVisible(false);
            frameConcluirChamado.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um chamado!!!");
        }
        
        
        
        
    }//GEN-LAST:event_button2ActionPerformed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jLabel16MousePressed

    private void btnEnviarAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarAvisoActionPerformed
        gravaAviso();

        try {
            AvisoDAO.cadastraAviso(dadosAviso);
            limpaCamposAviso();
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Não foi possível registrar o chamado!!!");
        }
    }//GEN-LAST:event_btnEnviarAvisoActionPerformed

    private void jLabel22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MousePressed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jLabel22MousePressed

    private void txtNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeFocusGained
        txtNome.setText("");
    }//GEN-LAST:event_txtNomeFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        txtUsuario.setText("");
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        txtSenha.setText("");
    }//GEN-LAST:event_txtSenhaFocusGained

    private void jLabel32MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MousePressed
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja realmente sair?", "Sair", JOptionPane.YES_NO_OPTION);

        if (opcao == JOptionPane.YES_OPTION) {
            System.exit(0);
        } else {

        }
    }//GEN-LAST:event_jLabel32MousePressed

    private void btnAlterarChamado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarChamado1ActionPerformed

        dadosChamado.setUrgencia(jcbUrgencia.getSelectedItem().toString());
        dadosChamado.setImpacto(jcbImpacto.getSelectedItem().toString());
        dadosChamado.setPrioridade(Integer.toString(verificaPrioridade()));

        if (jcbStatus.getSelectedIndex() == 0) {
            dadosChamado.setStatus("1");
        } else if (jcbStatus.getSelectedIndex() == 1) {
            dadosChamado.setStatus("2");
        } else if (jcbStatus.getSelectedIndex() == 2) {
            dadosChamado.setStatus("3");
        }
        

        try {
            ChamadoDAO.alteraChamado(dadosChamado);
            
            frameAlterarChamado.setVisible(false);
            frameGerenciarChamados.setVisible(true);
            
            carregaTabelaChamados();
            

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_btnAlterarChamado1ActionPerformed

    private void btnAlterarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarChamadoActionPerformed

        if (tblChamados.getSelectedRowCount() != 0) {

            dadosChamado.setID(tblChamados.getValueAt(tblChamados.getSelectedRow(), 0).toString());

            frameGerenciarChamados.setVisible(false);
            frameAlterarChamado.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um chamado!!!");
        }


    }//GEN-LAST:event_btnAlterarChamadoActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    private void jLabel36MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MousePressed

    private void txtNome1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNome1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome1FocusGained

    private void btnCadastrarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarUsuario1ActionPerformed
        String chamadoConcluido[] = new String[5];
        
        chamadoConcluido[0] = dadosChamado.getID();
        chamadoConcluido[1] = dadosChamado.getDataHora(0);
        chamadoConcluido[2] = dadosChamado.getDataHora(1);
        chamadoConcluido[3] = txtNome1.getText();
        chamadoConcluido[4] = jTextArea2.getText();
        
        try {
            dadosChamado = ChamadoDAO.consultaChamado(dadosChamado.getID());
            dadosChamado.setStatus("3");
            ChamadoDAO.alteraChamado(dadosChamado);
            
            ChamadoDAO.concluiChamado(chamadoConcluido);
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
        
        
        
        for (int i = 0; i < 5; i++) {
            System.out.println(chamadoConcluido[i]);
        }
        
        
        
    }//GEN-LAST:event_btnCadastrarUsuario1ActionPerformed

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(51, 175, 51));
    }

    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(0, 153, 50));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdm(LoginView.tmpLogin).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAlterarChamado;
    private java.awt.Button btnAlterarChamado1;
    private java.awt.Button btnCadastrarUsuario;
    private java.awt.Button btnCadastrarUsuario1;
    private javax.swing.JPanel btnCadastrarUsuarios;
    private java.awt.Button btnEnviarAviso;
    private javax.swing.JPanel btnGerenciarChamados;
    private javax.swing.JPanel btnNovoAviso;
    private javax.swing.JPanel btnSair;
    private java.awt.Button button2;
    private javax.swing.JInternalFrame frameAlterarChamado;
    private javax.swing.JInternalFrame frameCadastrarUsuario;
    private javax.swing.JInternalFrame frameConcluirChamado;
    private javax.swing.JInternalFrame frameGerenciarChamados;
    private javax.swing.JInternalFrame frameInserirAviso;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> jcbImpacto;
    private javax.swing.JComboBox<String> jcbSetor;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JComboBox<String> jcbUrgencia;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenha1;
    private javax.swing.JLabel lblSenha11;
    private javax.swing.JLabel lblSenha12;
    private javax.swing.JLabel lblSenha13;
    private javax.swing.JLabel lblSenha14;
    private javax.swing.JLabel lblSenha2;
    private javax.swing.JLabel lblSenha3;
    private javax.swing.JLabel lblSenha4;
    private javax.swing.JLabel lblSenha5;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JLabel lblUsuario11;
    private javax.swing.JLabel lblUsuario12;
    private javax.swing.JLabel lblUsuario13;
    private javax.swing.JLabel lblUsuario14;
    private javax.swing.JLabel lblUsuario2;
    private javax.swing.JLabel lblUsuario3;
    private javax.swing.JLabel lblUsuario4;
    private javax.swing.JLabel lblUsuario5;
    private javax.swing.JPanel pnlBarra;
    private javax.swing.JPanel pnlBarra1;
    private javax.swing.JPanel pnlBarra2;
    private javax.swing.JPanel pnlBarra3;
    private javax.swing.JPanel pnlBarra4;
    private javax.swing.JPanel pnlChamado;
    private javax.swing.JPanel pnlChamado1;
    private javax.swing.JPanel pnlChamado2;
    private javax.swing.JPanel pnlChamado3;
    private javax.swing.JPanel pnlChamado4;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JTable tblChamados;
    private javax.swing.JTextField txtAssunto;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtDescricaoAviso;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
